sudo: false

language: node_js
node_js: node

git:
  depth: 5

notifications:
  email: false

script: true

before_deploy:
  - openssl aes-256-cbc -K $encrypted_c5c534c0fd9c_key -iv $encrypted_c5c534c0fd9c_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d

deploy:
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
  on:
    repo: clippings/milan
    branch: master
    tags: true
